---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: drikkespillet
  name: drikkespillet
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: drikkespillet
  sessionAffinity: None
  type: ClusterIP
